'use strict';
try{require('dotenv').config({path:require('path').join(__dirname,'..','..', '.env')});}catch{}
const TOKEN=(process.env.TELEGRAM_BOT_TOKEN||'').trim();
const ADMIN_ID=String(process.env.TELEGRAM_ADMIN_ID||'');
const APP_URL=(process.env.APP_URL||'http://localhost:4000').replace(/\/$/,'');
const ADMIN_SECRET=(process.env.ADMIN_SECRET||'').trim();
if(!TOKEN||!ADMIN_ID||!ADMIN_SECRET){console.error('[FATAL] Missing env vars');process.exit(1);}
const https=require('https'),http=require('http');
function tg(method,body={}){return new Promise((resolve)=>{const data=JSON.stringify(body);const req=https.request({hostname:'api.telegram.org',path:`/bot${TOKEN}/${method}`,method:'POST',headers:{'Content-Type':'application/json','Content-Length':Buffer.byteLength(data)}},res=>{let raw='';res.on('data',c=>raw+=c);res.on('end',()=>{try{resolve(JSON.parse(raw));}catch{resolve({});}});});req.on('error',()=>resolve({}));req.write(data);req.end();});}
const send=(chat_id,text,extra={})=>tg('sendMessage',{chat_id:Number(chat_id),text,parse_mode:'HTML',...extra});
function generateInvite(){return new Promise((resolve,reject)=>{const body=JSON.stringify({expires_days:7});let url;try{url=new URL(`${APP_URL}/api/admin/invite`);}catch(e){return reject(new Error('Invalid APP_URL'));}const lib=url.protocol==='https:'?https:http;const opts={hostname:url.hostname,port:url.port?Number(url.port):(url.protocol==='https:'?443:80),path:url.pathname,method:'POST',headers:{'Content-Type':'application/json','Content-Length':Buffer.byteLength(body),'x-admin-secret':ADMIN_SECRET}};const req=lib.request(opts,res=>{let raw='';res.on('data',c=>raw+=c);res.on('end',()=>{try{const p=JSON.parse(raw);if(p.error)return reject(new Error(p.error));resolve(p);}catch{reject(new Error('Bad response: '+raw.slice(0,100)));}});});req.on('error',reject);req.write(body);req.end();});}
const pending={};
async function handle(update){
  console.log('[UPDATE]',JSON.stringify(update).slice(0,200));
  if(update.callback_query){const cb=update.callback_query;await tg('answerCallbackQuery',{callback_query_id:cb.id});const[action,userId]=(cb.data||'').split(':');const r=pending[userId];const edit=text=>tg('editMessageText',{chat_id:cb.message.chat.id,message_id:cb.message.message_id,text,parse_mode:'HTML'});if(!r){await edit('⚠️ Already handled.');return;}
    if(action==='approve'){try{const inv=await generateInvite();delete pending[userId];await send(userId,`🎉 <b>You're invited to OpenWave!</b>\n\nYour personal invite link — valid 7 days, one use only:\n\n<code>${inv.link}</code>\n\nOpen it in your browser and welcome 🌊`);await edit(`${cb.message.text}\n\n✅ <b>Approved</b> — invite sent`);}catch(err){await send(ADMIN_ID,`❌ Failed: ${err.message}`);}}
    if(action==='deny'){delete pending[userId];await send(userId,`Hi ${r.name},\n\nYour OpenWave invite request was declined. Feel free to try again.`);await edit(`${cb.message.text}\n\n❌ <b>Denied`);}
    return;}
  const msg=update.message;if(!msg?.text)return;
  const userId=String(msg.from.id),name=[msg.from.first_name,msg.from.last_name].filter(Boolean).join(' ')||'User',username=msg.from.username?`@${msg.from.username}`:'(no username)',text=msg.text.trim();
  console.log(`[MSG] from ${userId} (${name}): ${text.slice(0,80)}`);
  if(text==='/start'){if(pending[userId]?.step==='waiting'){await send(msg.chat.id,'⏳ Your request is pending. I\'ll message you when reviewed.');return;}pending[userId]={name,username,step:'awaiting_reason'};await send(msg.chat.id,`👋 <b>Hey ${name}!</b>\n\nThis bot handles invite requests for <b>OpenWave</b> — a private messenger.\n\nTell me <b>who you are and why you'd like to join</b>. The owner reviews every request personally.`);return;}
  if(text==='/status'){await send(msg.chat.id,pending[userId]?'⏳ Your request is pending.':'No pending request. Send /start to apply.');return;}
  if(text==='/test'&&userId===ADMIN_ID){await send(msg.chat.id,`🔍 Testing...\nAdmin ID: <code>${ADMIN_ID}</code>\nApp: <code>${APP_URL}</code>`);try{const inv=await generateInvite();await send(msg.chat.id,`✅ Connection works!\nTest link: <code>${inv.link}</code>`);}catch(err){await send(msg.chat.id,`❌ Error: ${err.message}`);}return;}
  if(text.startsWith('/invite')&&userId===ADMIN_ID){try{const inv=await generateInvite();await send(msg.chat.id,`✅ Invite:\n<code>${inv.link}</code>`);}catch(err){await send(msg.chat.id,`❌ ${err.message}`);}return;}
  if(text==='/pending'&&userId===ADMIN_ID){const list=Object.entries(pending);if(!list.length){await send(msg.chat.id,'No pending requests.');return;}await send(msg.chat.id,`<b>${list.length} pending:</b>\n\n${list.map(([id,r])=>`• <b>${r.name}</b> ${r.username}\n  ID: <code>${id}</code>\n  "${r.reason||'not yet provided'}"`).join('\n\n')}`);return;}
  if(text==='/whoami'&&userId===ADMIN_ID){await send(msg.chat.id,`👤 You are the admin\nYour ID: <code>${userId}</code>\nPending: ${Object.keys(pending).length}\nApp: ${APP_URL}`);return;}
  if(pending[userId]?.step==='awaiting_reason'){if(text.length<10){await send(msg.chat.id,'Please write a bit more — a sentence about yourself.');return;}pending[userId].reason=text;pending[userId].step='waiting';await send(msg.chat.id,'✅ <b>Request submitted!</b>\n\nThe owner will review it personally. You\'ll get a message here when approved or declined.\n\nUse /status to check anytime.');await send(ADMIN_ID,`📬 <b>New invite request</b>\n\n<b>Name:</b> ${name}\n<b>Telegram:</b> ${username}\n<b>User ID:</b> <code>${userId}</code>\n\n<b>Message:</b>\n"${text}"`,{reply_markup:{inline_keyboard:[[{text:'✅ Approve & send invite',callback_data:`approve:${userId}`},{text:'❌ Deny',callback_data:`deny:${userId}`}]]}});return;}
  if(!pending[userId])await send(msg.chat.id,'Send /start to request an invite to OpenWave.');else await send(msg.chat.id,'⏳ Your request is pending. Use /status to check.');
}
let offset=0;
async function poll(){try{const res=await tg('getUpdates',{offset,timeout:25,allowed_updates:['message','callback_query']});if(res.ok&&Array.isArray(res.result)){for(const u of res.result){offset=u.update_id+1;handle(u).catch(e=>console.error('[HANDLE]',e.message));}}}catch(e){console.error('[POLL]',e.message);await new Promise(r=>setTimeout(r,5000));}setTimeout(poll,200);}
async function start(){console.log('[START] Connecting...');const me=await tg('getMe');if(!me.ok){console.error('[FATAL] Invalid token');process.exit(1);}console.log(`[START] Bot: @${me.result.username}\n[START] Admin: ${ADMIN_ID}\n[START] App: ${APP_URL}`);await tg('deleteWebhook',{drop_pending_updates:false});await tg('setMyCommands',{commands:[{command:'start',description:'Request an invite to OpenWave'},{command:'status',description:'Check your request status'}]}).catch(()=>{});await send(ADMIN_ID,`🟢 <b>OpenWave Bot started</b>\n\nConnected to: <code>${APP_URL}</code>\nAdmin ID: <code>${ADMIN_ID}</code>\n\n/test — verify connection\n/invite — generate invite\n/pending — list requests`);poll();}
start().catch(e=>{console.error('[FATAL]',e.message);process.exit(1);});
